version: '3'

services:
    php-fpm:
        build:
            context: '.'
            dockerfile: './.docker/php-fpm/Dockerfile'

    nginx:
        build:
            context: '.'
            dockerfile: './.docker/nginx/Dockerfile'
        depends_on:
            - 'php-fpm'
        ports:
            - '8090:80'

    cloudflared:
        build:
            context: './.docker/cloudflared'
        depends_on:
            - 'nginx'
        command:
            - 'tunnel'
            - '--url=http://nginx:80'
            - '--loglevel=debug'
            - '--no-autoupdate'
